### ISSUE TITLE
test-and-upgrade command shoud drop the qwat_test DB ?

### ISSUE THREAD

**Issue by sylvainbeo** [opengisch/pum#12]
Launch the command :

`pum test-and-upgrade -pp qwat_prod -pt qwat_test -pc qwat_comp -t qwat_sys.info -d /home/sbe/projects/qwat_project/data-model/update/delta/ -f /home/sbe/tmp/qwat_dump -i columns constraints views sequences indexes triggers functions rules`

Should pum drop and recreate the qwat_test DB by its own ? 
Because, if the command fail, we have to drop and recreate the qwta_test DB manually.

**Comment by haubourg** [comment]
Hi, same issue here. 
Maybe not dropping, but using pg_restore --clean option could work?

**Comment by ponceta** [comment]
Same here.

**Comment by sylvainbeo** [comment]
@marioba @m-kuhn @elemoine Any thought on that ?

**Comment by elemoine** [comment]
If test-and-upgrade did not create the test database I don't think it should drop it.

**Comment by sylvainbeo** [comment]
@elemoine Well then we have to find a good way to manage that. Because this is very disturbing when using PUM. You always forget to drop and recreate the DB manually, and you've got errors, and for a few minutes you don't understand the errors...

**Comment by elemoine** [comment]
To me this is an issue on the Pum user side.

**Comment by sylvainbeo** [comment]
Ok, we've discuss this. I'm closing this ticket. See https://github.com/qwat/qwat-data-model/issues/223 for more.
