### ISSUE TITLE
pum .info is not seeing post-all.sql files

### ISSUE THREAD

**Issue by haubourg** [opengisch/pum#14]
Just checking a directory with only a post-all.sql and pum.info is not listing it nor pum upgrade applies.

**Comment by marioba** [comment]
Currently, pum is delta-file-centric. If no delta files are present, pum considers that there is nothing to do. Only if there are delta files, it looks for pre-all and post-all. 
Changing this involves several changes to the code. 
Do you think is it really necessary?

**Comment by haubourg** [comment]
Ok thanks for the explanations, don't do anything more!
