### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by ponceta** [opengisch/pum#15]
Since it has been advised yesterday to support python 3 only, I would recommend mentionning this into the readme.

Then the install command is usually `pip3 intall pum`

**Comment by ponceta** [comment]
I could install pum but can't run it

pulmexa@ubuntu:~/qwat-data-model$ pum check -p1 qwat -p2 qwat_test
No command 'pum' found, did you mean:
...

I looked up to virtual environments using venv, sets my python default to python3 which is great but does not fix my path to pum!

https://docs.python.org/3/tutorial/venv.html

**Comment by m-kuhn** [comment]
Just pushed a commit that will the abort the installation and warn when installing pum on Python<3.3

**Comment by m-kuhn** [comment]
Can you try

```
mkdir .virtualenv
virtualenv -p python3 ~/.virtualenv/pum
source ~/.virtualenv/pum/bin/activate
pum --version
```

**Comment by ponceta** [comment]
I could install pum using venv and it works.

I still have to test it using qwat upgrade script

**Comment by m-kuhn** [comment]
```
source /tmp/python2/bin/activate
 mkuhn  (e) python2  ~  pip install pum
Collecting pum
  Using cached pum-0.5.5.tar.gz
    Complete output from command python setup.py egg_info:
    Pum requires at least Python version 3.3.
    You are currently running this installation with
    
    2.7.14 (default, Nov  3 2017, 10:55:25)
    [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

```
source /tmp/python3/bin/activate
 mkuhn  (e) python3  ~  pip install pum
Collecting pum
  Using cached pum-0.5.5.tar.gz
Collecting psycopg2>=2.7.3 (from pum)
  Using cached psycopg2-2.7.3.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting PyYAML (from pum)
Building wheels for collected packages: pum
  Running setup.py bdist_wheel for pum ... done
  Stored in directory: /home/mkuhn/.cache/pip/wheels/92/a6/78/4a0a35a0bed404d979d9d7dc0dc35c8dc67088103ead7f9b88
Successfully built pum
Installing collected packages: psycopg2, PyYAML, pum
Successfully installed PyYAML-3.12 psycopg2-2.7.3.2 pum-0.5.5
```

**Comment by haubourg** [comment]
Nice! Thanks Matthias

**Comment by m-kuhn** [comment]
What's left to do?
Documentation about how to setup the path?

**Comment by haubourg** [comment]
Yes please, in PUM's readme

**Comment by m-kuhn** [comment]
Just tested `sudo pip3 install pum` makes it work here.
So it's hard for me to come up with installation instructions. Other takers?

**Comment by haubourg** [comment]
well, just tested also the opposite:
```
alias python=python2
python -V
> python 2.7


> pip install pumCollecting pum
> Requirement already up-to-date: psycopg2>=2.7.3 in /home/regis/APPS/python_venv/pyqwat/lib/python3.5/site-packages (from pum)
> Requirement already up-to-date: PyYAML in /home/regis/APPS/python_venv/pyqwat/lib/python3.5/site-packages (from pum)
> Installing collected packages: pum
> Successfully installed pum-0.5.4

```
where pip uses pip3 implicitly
so what messed me yesterday was the need to restart my terminal. 
Sooo....  I guess I should go to informatic's school (which I never did)

**Comment by ponceta** [comment]
Activating venv for python 3 is a requirement here, this should be in the doc.

**Comment by m-kuhn** [comment]
This?

```
mkdir ~/.virtualenv
virtualenv -p python3 ~/.virtualenv/pum
source ~/.virtualenv/pum/bin/activate
pip install pum
pum --version
```

**Comment by ponceta** [comment]
IMHO yes. Since python3 is maybe still new to users. Wouldn't be necessary if python3 was default.

**Comment by m-kuhn** [comment]
I can do the docs, but I need some confirmation that the easiest approach does actually NOT work (because it does work here):

    sudo pip3 install pum
    pum --version

And that the [above script](https://github.com/opengisch/pum/issues/15#issuecomment-346837814) can be copy/pasted on ubuntu system and actually does lead to a working environment.

**Comment by m-kuhn** [comment]
Thanks @haubourg 

I think a *default* python 3 env should not be required in any case. Just a *system* python 3 env (even if python 2 is the default).

Short question: What happens when you do

```
sudo pip3 install pum
pum --version
```

**Comment by ponceta** [comment]
pum is installed for python3 but since your default python env is using pip and python 2, the pum module is not found :

```
pulmexa@ubuntu:~$ pum -- version
No command 'pum' found, did you mean:
 Command 'sum' from package 'coreutils' (main)
 Command 'uum' from package 'freewnn-jserver' (universe)
 Command 'pom' from package 'bsdgames' (universe)
 Command 'bum' from package 'bum' (universe)
 Command 'pua' from package 'pglistener' (universe)
 Command 'plum' from package 'plum' (universe)
 Command 'pm' from package 'powerman' (universe)
 Command 'pump' from package 'pump' (universe)
 Command 'zum' from package 'perforate' (universe)
 Command 'pvm' from package 'pvm' (universe)
 Command 'pfm' from package 'pfm' (universe)
 Command 'yum' from package 'yum' (universe)
 Command 'puf' from package 'puf' (universe)
 Command 'plm' from package 'plm' (universe)
pum: command not found

```

**Comment by haubourg** [comment]
Exactly, on you need to change the default python with:
`alias python=python3`
see https://askubuntu.com/questions/590027/how-to-set-python-3-as-default-interpreter-in-ubuntu-14-04
all the three method are not straightforward and full of caveats. In upgrade_db.sh we raise now a hint for that.

```
PUM_VERSION=$(pum -v)
if [[ $PUM_VERSION == '' ]]; then
    printf "\t${RED}PUM is not installed${NC}\n"
    echo "Please install PUM compatible with Python 3 (pip install pum)"
    echo
    exit 0
fi
```

**Comment by m-kuhn** [comment]
What's the output of

```
sudo pip3 show -f pum
```

**Comment by haubourg** [comment]
OK, I checked what happened with Vincent Mora here. 
So what we have is that pip alias always points to pip2 version even if we have a python alias pointing to python3. 
In fact, the simplest way would be to change the pum README install instructions with
`pip3 install pum`

**Comment by m-kuhn** [comment]
Thanks @haubourg , does that mean you can confirm [this installation instruction](https://github.com/opengisch/pum/issues/15#issuecomment-347883469)?

**Comment by haubourg** [comment]
yep, not sure the sudo is mandatory though.

**Comment by m-kuhn** [comment]
without sudo the executable will be installed to `~/.local/bin/` which is not normally on `PATH`, so this would need to be documented as an additional step.

* the sudo approach is most straightforward (a single command)
* the virtualenv approach is most isolated

I guess we should document these two
