### ISSUE TITLE
pum and pg_service on remote db

### ISSUE THREAD

**Issue by ponceta** [opengisch/pum#17]
On Ubuntu 16.04
pum version 0.5.4

I face some issues using pum:

Using :

`psql "service=qwat_test"`

I can connect to my db without a problem.

`pum check -p1 qwat -p2 qwat_test`

Gets the diff correctly

`pum dump -p qwat_test /tmp/bak`

Gets a connection error : 

`b'pg_dump: [archiver (db)] connection to database "qwat_test" failed: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n'`

@marioba @m-kuhn @haubourg

**Comment by marioba** [comment]
I'm looking for this. Are you using Postgres 10?
`pg_dump --version`

**Comment by ponceta** [comment]
No postgres 9.4

**Comment by ponceta** [comment]
pg_dump (PostgreSQL) 9.4.15

**Comment by ponceta** [comment]
https://serverfault.com/questions/587905/using-pg-dump-when-connecting-via-a-service

**Comment by ponceta** [comment]
How do you handle pg_service and db connection in pum?

**Comment by marioba** [comment]
Thanks for the link. I never found how to pass the service to the pg_dump command. 
I will refactor and simplify the dumper class.

**Comment by marioba** [comment]
in the rest of pum something like `psycopg2.connect("service=servicename")` is used.

**Comment by marioba** [comment]
I fixed this. 
@m-kuhn how do you update the pip version?

**Comment by m-kuhn** [comment]
git tag

**Comment by haubourg** [comment]
in updateb_db.sh and other similar scripts, we do this ugly thing to get the db name from the service file

`DBCOMP_NAME=$(sed -n -e "/^\[qwat_comp]/,/^\[/ p" ~/.pg_service.conf | grep "^dbname" | cut -d"=" -f2)`

**Comment by marioba** [comment]
It's in the 0.5.6 release.

**Comment by ponceta** [comment]
If someone goes by here looking for update:

`sudo pip install pum --upgrade`

Is the syntax to update pum if python 3 venv is active.

else :

`sudo pip3 install pum --upgrade`

**Comment by ponceta** [comment]
```
(tutorial-env) pulmexa@ubuntu:~$ pum dump -p qwat_test /tmp/bak
Dump...OK
```

Works!
