### ISSUE TITLE
Run unit tests

### ISSUE THREAD

**Issue by elemoine** [opengisch/pum#21]
The README file doesn't include instructions for running unit tests. How can I run unit tests?

Sorry if issues are not the best way to ask questions. I haven't found a better way.

**Comment by marioba** [comment]
Hi @elemoine, to run one test you can do something similar to
`python -m unittest test/test_checker.py` 
or `python -m unittest discover test/` to run all the tests.

In each test module you should find an indication of the db needed for the test.
I hope this helps you.

**Comment by elemoine** [comment]
Thanks @marioba. That helped.

I found out that I need to re-create the test databases before an execution of a test script. Otherwise the tests may fail because of things left in the databases by the previous test run. Work for a future PR I guess.
