### ISSUE TITLE
restore fails without returning an error

### ISSUE THREAD

**Issue by 3nids** [opengisch/pum#40]
see https://travis-ci.org/QGEP/datamodel/jobs/363564290#L1878

**Comment by 3nids** [comment]
![image](https://user-images.githubusercontent.com/127259/38495984-bb4f3706-3bc9-11e8-9cdc-845c466e757b.png)

**Comment by marioba** [comment]
It's correct. The option `-x` means `ignore pg_restore errors`.

**Comment by 3nids** [comment]
hmmm, but I added an exit_on_error....
fixed in 5870ceb2bc4fc8bcdab8e7a675abc9d2cd5d6f33
