### ISSUE TITLE
Explain pg_service definition in README.md

### ISSUE THREAD

**Issue by volcan01010** [opengisch/pum#43]
Hi,

I wanted to try out PUM but I can't understand how the database connections are defined.  Can you please add an explanation to the README.md?

I managed to see that psycopg2 calls the service as `psycopg2.connect(service={})`, but there is no mention of this syntax in the psycopg2 docs.  http://initd.org/psycopg/docs/module.html?highlight=connect#psycopg2.connect

I eventually found PostgreSQL docs describing the `pg_service.conf` file: https://www.postgresql.org/docs/current/static/libpq-pgservice.html

Is there a recommended way to use it?  Should you store the password there or pass it in another way e.g. via PGPASSWORD variable?

Can you please add some text on this to the REAME.md docs?

**Comment by sjib** [comment]
pg_service.conf is a good way.
Here the info for  a password file https://www.postgresql.org/docs/current/static/libpq-pgpass.html

**Comment by 3nids** [comment]
Here is the content of the README:
![image](https://user-images.githubusercontent.com/127259/42698411-19ce34a0-86be-11e8-8290-38db73300edf.png)

I added a few links to be more explicit.

Thanks for raising this.

**Comment by 3nids** [comment]
and yes, password can be stored in the same file.
see https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS for complete info.
