### ISSUE TITLE
Explain the baseline better

### ISSUE THREAD

**Issue by sylvainbeo** [opengisch/pum#6]
There is a technical explanation on how to use the baseline, but no 'human' explanation of what it is.

By the way, i tried to execute it :

```
pum.py baseline -p qwat -t qwat_sys.baseline -d /path_to_deltas/ -b v22
```
Results in a crash
```

  File "./pum.py", line 180, in run_baseline
    raise Exception

```

I think some informations messages are missing in your exceptions.

Thanks.

**Comment by marioba** [comment]
Thanks for the note, the baseline must be in the format *x.x.x* p.ex `1.0.0`
I will add a check to verify the right format and improve the output in case of an exception.

**Comment by marioba** [comment]
Now is better explained and I add a check if the version number is in the right format.

**Comment by sylvainbeo** [comment]
Thnak you. I'll have a look.
