### ISSUE TITLE
pum -x does not ignore pg_restore issues anymore (0.9.7)

### ISSUE THREAD

**Issue by ponceta** [opengisch/pum#67]
(pum 0.9.7 / ubuntu 18.04 x64 )
Using 

pum test-and-upgrade -x -pp qwat_prod -pt qwat_test -pc qwat_comp -t qwat_sys.info -d delta/ -f /tmp/qwat_dump -i views rules

To update qwat gets me pg_restore errors although I set -x flag to avoid these. 

`pum.core.exceptions.PgRestoreFailed: b'pg_restore: [archiver (db)] Error while PROCESSING TOC:\npg_restore: [archiver (db)] Error from TOC entry 4172; 0 268291 TABLE DATA spatial_ref_sys postgres\npg_restore: [archiver (db)] COPY failed for table "spatial_ref_sys": ERREUR:  la valeur d\'une cl\xc3\xa9 dupliqu\xc3\xa9e rompt la contrainte unique \xc2\xab spatial_ref_sys_pkey \xc2\xbb\nDETAIL:  La cl\xc3\xa9 \xc2\xab (srid)=(5228) \xc2\xbb existe d\xc3\xa9j\xc3\xa0.\nCONTEXT:  COPY spatial_ref_sys, ligne 1\nWARNING: errors ignored on restore: 1\n'`

AttributeError: 'PgRestoreFailed' object has no attribute 'output'

**Comment by 3nids** [comment]
this is fixed.
but you should consider excluding the public schema from the restore to avoid these.

**Comment by haubourg** [comment]
>  but you should consider excluding the public schema from the restore to avoid these.

+1 this is a very good practice

**Comment by ponceta** [comment]
> this is fixed.
> but you should consider excluding the public schema from the restore to avoid these.

I would for sure, but it's not me who's dumping and restoring! It's PUM! :S

https://github.com/opengisch/pum/issues/69
